#!/bin/sh
FORMAT="$1"
[ -n "$2" ] && SHORTFORMAT="$2" || SHORTFORMAT="$1"

cat <<EOF
%package ${FORMAT}
Summary: Qt 5.x support for images in the ${FORMAT} format
Group: System/Libraries

%description ${FORMAT}
Qt 5.x support for images in the ${FORMAT} format

%files ${FORMAT}
%{_libdir}/qt5/plugins/imageformats/kimg_${FORMAT}.so
%{_datadir}/kde5/services/qimageioplugins/${SHORTFORMAT}.desktop
EOF
